import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

// P1.14 architecture guards for the admin UI — WARNINGS for now (existing code migrates module by module in P2+); they
// stop new code from re-growing what P1 centralised. The navigation, shortcut and status guards are tests
// (tests/architecture/*.test.ts) and fail the build.
const ADMIN_UI = ["app/admin/**/*.{ts,tsx}", "components/admin/**/*.{ts,tsx}"];
const adminArchitecture = [
  {
    selector: "BinaryExpression[operator=/^[!=]==$/] > MemberExpression[property.name='role']",
    message: "Don't branch on the admin's role in the UI — ask useCapability() (lib/admin/capabilities.ts); the API enforces permissions.",
  },
  {
    selector: "JSXOpeningElement[name.name='table']",
    message: "New list screens use DataTable (components/admin/data-table) or the Table primitives (components/ui/table.tsx), not a bespoke <table>.",
  },
  {
    selector: "NewExpression[callee.name='URLSearchParams'] > MemberExpression[property.name='search'][object.property.name='location']",
    message: "Read view state with useUrlState(schema) (hooks/use-url-state.ts) instead of parsing window.location.search by hand.",
  },
];

const config = [
  // next-env.d.ts is regenerated by `next dev`/`next build` on every run — not a source file to lint.
  { ignores: [".next/**", "node_modules/**", "playwright-report/**", "test-results/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // This codebase's existing convention for "required by a callback signature, deliberately
      // unused" (e.g. onAltSuccess(_customer: Customer) — the caller always passes it).
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
  {
    files: ADMIN_UI,
    rules: {
      "no-restricted-syntax": ["warn", ...adminArchitecture],
      "no-restricted-imports": [
        "warn",
        {
          paths: [
            {
              name: "@/lib/auth",
              importNames: ["adminCan"],
              message: "Use useCapability() / useCapabilities() (hooks/use-capability.ts) — the capability registry maps onto the server permissions.",
            },
          ],
        },
      ],
    },
  },
  {
    // The infrastructure these guards point to.
    files: ["components/admin/data-table/**", "components/admin/filters/**"],
    rules: { "no-restricted-syntax": "off" },
  },
];

export default config;
