import {
  Award,
  BadgeCheck,
  Banknote,
  Calendar,
  CheckCircle,
  Clock,
  CreditCard,
  Feather,
  Gem,
  Gift,
  Globe,
  Handshake,
  Headphones,
  Heart,
  Leaf,
  Lock,
  Mail,
  MapPin,
  Medal,
  MessageCircle,
  Package,
  PackageCheck,
  Percent,
  PhoneCall,
  Recycle,
  RotateCcw,
  Ruler,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Snowflake,
  Sparkle,
  Sparkles,
  Star,
  Sun,
  Tag,
  ThumbsUp,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** String keys are what `HomepageSection.config` stores (JSON can't hold a component reference) —
 * this is the single lookup both the storefront (TrustStrip/ValuesGrid) and the admin builder's
 * icon picker resolve against, so the two stay in sync. Curated (not the full ~1500-icon Lucide
 * set) to keep the picker scannable — every entry here should be plausible on a trust badge or
 * value-prop card for a clothing store. */
export const HOMEPAGE_ICON_MAP: Record<string, LucideIcon> = {
  Truck,
  RotateCcw,
  ShieldCheck,
  Banknote,
  Feather,
  Ruler,
  Gem,
  Leaf,
  Star,
  Heart,
  Award,
  CheckCircle,
  Clock,
  Package,
  Zap,
  Gift,
  PackageCheck,
  CreditCard,
  Wallet,
  Tag,
  Percent,
  BadgeCheck,
  Lock,
  MapPin,
  Headphones,
  MessageCircle,
  ThumbsUp,
  TrendingUp,
  Recycle,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Users,
  Globe,
  Handshake,
  Medal,
  Trophy,
  Calendar,
  Timer,
  Sun,
  Snowflake,
  PhoneCall,
  Mail,
  Sparkle,
  Sparkles,
};

export const HOMEPAGE_ICON_NAMES = Object.keys(HOMEPAGE_ICON_MAP);

export function resolveHomepageIcon(name: string): LucideIcon {
  return HOMEPAGE_ICON_MAP[name] ?? Sparkles;
}
